
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Mar 10 20:50:08 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 45;
  public static final int LBRACKET = 26;
  public static final int CHAR = 52;
  public static final int CONST = 3;
  public static final int QUESTIONMARK = 32;
  public static final int CASE = 14;
  public static final int LPAREN = 24;
  public static final int SEMI = 28;
  public static final int CONTINUE = 9;
  public static final int FOR = 15;
  public static final int MINUS = 34;
  public static final int RPAREN = 25;
  public static final int AND = 47;
  public static final int LT = 44;
  public static final int OR = 46;
  public static final int BOOL = 53;
  public static final int COMMA = 29;
  public static final int INC = 38;
  public static final int DIV = 36;
  public static final int PLUS = 33;
  public static final int IF = 6;
  public static final int DOT = 31;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 48;
  public static final int RBRACKET = 27;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int MUL = 35;
  public static final int NUMBER = 50;
  public static final int MOD = 37;
  public static final int NEQ = 41;
  public static final int IDENT = 51;
  public static final int BREAK = 8;
  public static final int VOID = 5;
  public static final int EQ = 40;
  public static final int GTE = 43;
  public static final int SWITCH = 13;
  public static final int FOREACH = 19;
  public static final int COLON = 30;
  public static final int LBRACE = 22;
  public static final int ELSE = 7;
  public static final int ENUM = 4;
  public static final int READ = 11;
  public static final int GOTO = 21;
  public static final int WHILE = 17;
  public static final int DEFAULT = 20;
  public static final int RBRACE = 23;
  public static final int PROG = 2;
  public static final int LEN = 49;
  public static final int DEC = 39;
  public static final int GT = 42;
  public static final int PRINT = 12;
  public static final int DO = 18;
}

