
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Mar 08 15:22:43 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 40;
  public static final int LBRACKET = 21;
  public static final int CHAR = 47;
  public static final int CONST = 3;
  public static final int QUESTIONMARK = 27;
  public static final int CASE = 14;
  public static final int LPAREN = 19;
  public static final int SEMI = 23;
  public static final int CONTINUE = 9;
  public static final int FOR = 15;
  public static final int MINUS = 29;
  public static final int RPAREN = 20;
  public static final int AND = 42;
  public static final int LT = 39;
  public static final int OR = 41;
  public static final int BOOL = 48;
  public static final int COMMA = 24;
  public static final int INC = 33;
  public static final int DIV = 31;
  public static final int PLUS = 28;
  public static final int IF = 6;
  public static final int DOT = 26;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 43;
  public static final int RBRACKET = 22;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int MUL = 30;
  public static final int NUMBER = 45;
  public static final int MOD = 32;
  public static final int NEQ = 36;
  public static final int IDENT = 46;
  public static final int BREAK = 8;
  public static final int VOID = 5;
  public static final int EQ = 35;
  public static final int GTE = 38;
  public static final int SWITCH = 13;
  public static final int COLON = 25;
  public static final int LBRACE = 17;
  public static final int ELSE = 7;
  public static final int ENUM = 4;
  public static final int READ = 11;
  public static final int RBRACE = 18;
  public static final int PROG = 2;
  public static final int LEN = 44;
  public static final int DEC = 34;
  public static final int GT = 37;
  public static final int PRINT = 12;
}

